provider:
  name: faas
  gateway: http://localhost:8080
  network: "func_functions" # this is optional and defaults to func_functions

functions:
  figlet:
    image: jmkhael/faas-figlet
    fprocess: figlet
